version: '3'

services: 

  back-end:
    build: 
      context: server
    container_name: back-end
    working_dir: /usr/src/app
    networks: 
      - database-postgres_node-network
    tty: true
    ports: 
      - "3000:3000"
    expose:
      - "3000"
    command: npm run dev

  front-end:
    build: 
      context: client
    container_name: front-end
    working_dir: /usr/src/app
    networks: 
      - database-postgres_node-network
    tty: true
    ports: 
      - "5173:5173"
    command: npm run preview -- --host

  nginx:
    build: 
      context: nginx
    container_name: nginx
    restart: always
    tty: true
    volumes:
      - ./fullchain.pem:/etc/ssl/certs/fullchain.pem
      - ./privkey.pem:/etc/ssl/private/privkey.pem
    ports: 
      - "80:80"
      - "443:443"
    networks: 
      - database-postgres_node-network
    depends_on:
       - back-end
       - front-end

networks: 
  database-postgres_node-network:
    external: true
