version: '3.8'

services: 

  db:
    image: postgres
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    environment: 
      - POSTGRES_PASSWORD=1234
    ports: 
      - "5432:5432"
    networks: 
      - database-postgres_bridge

  back-end:
    build: 
      context: server
    container_name: back-end
    working_dir: /usr/src/app
    networks: 
      - database-postgres_bridge
    tty: true
    ports: 
      - "3000:3000"
    expose:
      - "3000"
    command: npm run dev

  front-end:
    build: 
      context: client
    container_name: front-end
    working_dir: /usr/src/app
    networks: 
      - database-postgres_bridge
    tty: true
    ports: 
      - "5173:5173"
    command: npm run preview -- --host

  nginx:
    build: 
      context: nginx
    container_name: nginx
    restart: always
    tty: true
    volumes:
      - ./fullchain.pem:/etc/ssl/certs/fullchain.pem
      - ./privkey.pem:/etc/ssl/private/privkey.pem
    ports: 
      - "80:80"
      - "443:443"
    networks: 
      - database-postgres_bridge
    depends_on:
       - back-end
       - front-end

networks:
  database-postgres_bridge:
