version: '3'

services: 

  back-end:
    build: 
      context: server
    container_name: back-end
    working_dir: /usr/src/app
    volumes: 
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports: 
      - "3000:3000"
    expose:
      - "3000"
    command: npm install


  front-end:
    build: 
      context: client
    container_name: front-end
    working_dir: /usr/src/app
    tty: true
    ports: 
      - "5173:5173"
    command: npm run preview -- --host #para produccion
    depends_on:
       - back-end

  nginx:
    build: 
      context: nginx
    container_name: nginx
    restart: always
    tty: true
    volumes:
      - ./fullchain.pem:/etc/ssl/certs/fullchain.pem
      - ./privkey.pem:/etc/ssl/private/privkey.pem
    ports: 
      - "80:80"
      - "443:443"
    depends_on:
       - back-end
       - front-end

