version: '3'

services: 

  back-end:
    build: 
      context: server
    container_name: back-end
    working_dir: /usr/src/app
    tty: true
    ports: 
      - "3000:3000"
    expose:
      - "3000"
    command: npm run dev
    # depends_on:
    #    - db

  front-end:
    build: 
      context: client
    container_name: front-end
    working_dir: /usr/src/app
    tty: true
    ports: 
      - "5173:5173"
    command: npm run preview -- --host #para produccion

  nginx:
    build: 
      context: nginx
    container_name: nginx
    restart: always
    tty: true
    ports: 
      - "80:8000"
    depends_on:
       - back-end
       - front-end
