-- CreateEnum
CREATE TYPE "GENDER" AS ENUM ('MASCULINO', 'FEMENINO');

-- CreateEnum
CREATE TYPE "ROL" AS ENUM ('ADMINISTRADOR', 'EMPLEADO', 'CLIENTE');

-- CreateTable
CREATE TABLE "USER" (
    "Id" SERIAL NOT NULL,
    "User_Name" TEXT NOT NULL,
    "Email" TEXT NOT NULL,
    "Password" TEXT NOT NULL,
    "Role" "ROL" NOT NULL,
    "created_At" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_At" TIMESTAMP(3),

    CONSTRAINT "USER_pkey" PRIMARY KEY ("Id")
);

-- CreateTable
CREATE TABLE "PERSON" (
    "Id" SERIAL NOT NULL,
    "DNI" TEXT NOT NULL,
    "First_Name" TEXT NOT NULL,
    "Last_Name" TEXT NOT NULL,
    "Birth_Date" TEXT NOT NULL,
    "Phone_Number" TEXT,
    "Address" TEXT,
    "Gender" "GENDER" NOT NULL,
    "Created_At" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "Updated_At" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "PERSON_pkey" PRIMARY KEY ("Id")
);

-- CreateTable
CREATE TABLE "EMPLOYEE" (
    "Id" SERIAL NOT NULL,
    "Phone" TEXT,
    "Email" TEXT NOT NULL,
    "Password" TEXT,
    "Salary" DOUBLE PRECISION NOT NULL,
    "Person_Fk" INTEGER NOT NULL,
    "User_Fk" INTEGER NOT NULL,
    "Created_At" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "Updated_At" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "EMPLOYEE_pkey" PRIMARY KEY ("Id")
);

-- CreateTable
CREATE TABLE "CLIENT" (
    "Id" SERIAL NOT NULL,
    "Person_Fk" INTEGER NOT NULL,
    "User_Fk" INTEGER NOT NULL,
    "Created_At" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "Updated_At" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "CLIENT_pkey" PRIMARY KEY ("Id")
);

-- CreateTable
CREATE TABLE "ADMIN" (
    "Id" SERIAL NOT NULL,
    "Email" TEXT NOT NULL,
    "Password" TEXT NOT NULL,
    "Person_Fk" INTEGER NOT NULL,
    "User_Fk" INTEGER NOT NULL,
    "Created_At" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "Updated_At" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ADMIN_pkey" PRIMARY KEY ("Id")
);

-- CreateIndex
CREATE UNIQUE INDEX "USER_Email_key" ON "USER"("Email");

-- CreateIndex
CREATE UNIQUE INDEX "PERSON_DNI_key" ON "PERSON"("DNI");

-- CreateIndex
CREATE UNIQUE INDEX "EMPLOYEE_Email_key" ON "EMPLOYEE"("Email");

-- CreateIndex
CREATE UNIQUE INDEX "ADMIN_Email_key" ON "ADMIN"("Email");

-- AddForeignKey
ALTER TABLE "EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_Person_Fk_fkey" FOREIGN KEY ("Person_Fk") REFERENCES "PERSON"("Id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_User_Fk_fkey" FOREIGN KEY ("User_Fk") REFERENCES "USER"("Id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CLIENT" ADD CONSTRAINT "CLIENT_Person_Fk_fkey" FOREIGN KEY ("Person_Fk") REFERENCES "PERSON"("Id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CLIENT" ADD CONSTRAINT "CLIENT_User_Fk_fkey" FOREIGN KEY ("User_Fk") REFERENCES "USER"("Id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ADMIN" ADD CONSTRAINT "ADMIN_Person_Fk_fkey" FOREIGN KEY ("Person_Fk") REFERENCES "PERSON"("Id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ADMIN" ADD CONSTRAINT "ADMIN_User_Fk_fkey" FOREIGN KEY ("User_Fk") REFERENCES "USER"("Id") ON DELETE RESTRICT ON UPDATE CASCADE;
