name: CI Pipeline

on:
  push:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Pull Docker image
      run: sudo docker-compose pull
    - name: Delete Old Docker container
      run: sudo docker rm -f $(docker ps -aq)
    - name: Delete Old Docker images
      run: sudo docker rmi -f $(docker images -aq)
    - name: Run Docker compose up
      run: sudo docker-compose up -d
    - name: Restaurar datos DB
      run: sudo cat dump.sql | docker exec -i db psql -U postgres