name: Docker CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Build & Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USER}}
          key: ${{secrets.SSH_KEY}}
          port: ${{secrets.SSH_PORT}}
          script: |
            echo "${{secrets.SSL_CERTIFICATE}}" > fullchain.pem
            echo "${{secrets.SSL_CERTIFICATE_KEY}}" > privkey.pem
            git checkout master 
            git pull origin master 
            sudo usermod -aG docker $USER 
            if [ $(sudo docker ps -q -f name=nginx) ]; then
              sudo docker stop nginx
            fi
            if [ $(sudo docker ps -q -f name=back-end) ]; then
              sudo docker stop back-end
            fi
            if [ $(sudo docker ps -q -f name=front-end) ]; then
              sudo docker stop front-end
            fi
            if [ $(sudo docker ps -q -f name=pgadmin) ]; then
              sudo docker stop pgadmin
            fi
            sudo docker-compose up --build -d 
