name: Docker CI/CD Pipeline

on:
  push:
    branches: [ "master" ]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v2 
      - name: Change permissions
        run: sudo rm -rf dbdata
      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.SSH_KEY }}
            HOSTNAME: ${{secrets.EC2_HOST}}
            USER_NAME: ${{secrets.USERNAME}}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem && chmod 600 private_key.pem &&
          ssh -i "private_key.pem" ubuntu@ec2-34-229-95-96.compute-1.amazonaws.com &&
    
          cd /home/ubuntu/classicvision &&
          git checkout master &&
          git fetch --all &&
          git reset --hard origin/master &&
          git pull origin master &&
          if [ "$(docker ps -a -q)" != "" ]; then
          sudo docker rm -f $(docker ps -a -q)
          fi
          if [ "$(docker images -a -q)" != "" ]; then
          sudo docker rmi -f $(docker images -a -q)
          fi &&
          docker-compose.yml up -d --build &&