name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Remove old Docker images and containers
      run: |
        if [ "$(docker ps -a -q)" != "" ]; then
        sudo docker rm -f $(docker ps -a -q)
        fi
        if [ "$(docker images -a -q)" != "" ]; then
        sudo docker rmi -f $(docker images -a -q)
        fi
    - name: Build the Docker image
      run: sudo docker-compose up -d --build
    - name: Wait for PostgreSQL to become ready
      run: |
        for i in {1..10}; do
          if sudo docker exec db pg_isready -U postgres; then
            break
          fi
          echo "Waiting for PostgreSQL to become ready..."
          sleep 10
        done
    - name: Up DB data
      run: sudo cat dump.sql | docker exec -i db psql -U postgres