name: Docker CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Build & Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host:  ec2-3-221-247-199.compute-1.amazonaws.com
          username: ubuntu
          key: ${{secrets.SSH_KEY}}
          port: 22
          script: |
            cd Proyecto-Industria-Software/Proyecto-Industria-Software
            echo "${{secrets.SSL_CERTIFICATE}}" > fullchain.pem
            echo "${{secrets.SSL_CERTIFICATE_KEY}}" > privkey.pem
            git checkout master 
            git pull 
            sudo usermod -aG docker $USER 
            if [ $(sudo docker ps -q -f name=nginx) ]; then
              sudo docker stop nginx
            fi
            if [ $(sudo docker ps -q -f name=back-end) ]; then
              sudo docker stop back-end
            fi
            if [ $(sudo docker ps -q -f name=front-end) ]; then
              sudo docker stop front-end
            fi
            if [ $(sudo docker ps -q -f name=pgadmin) ]; then
              sudo docker stop pgadmin
            fi
            sudo docker-compose up --build -d 
            sudo docker network connect node-network back-end
            sudo docker network connect node-network front-end
            sudo docker network connect node-network nginx
            cat dump.sql | docker exec -i db psql -U postgres
            exit
