name: Docker CI/CD Pipeline

on:
  push:
    branches: [ "master" ]

jobs:
    Deploy:
        name: Deploy to EC2
        runs-on: self-hosted
    
        steps:
          - uses: actions/checkout@v2 
          - name: Build & Deploy
            run: |
              echo "${{secrets.SSH_KEY}}" > private_key.pem
              chmod 600 private_key.pem
              ssh -o StrictHostKeyChecking=no -i "private_key.pem" ubuntu@ec2-3-95-211-177.compute-1.amazonaws.com &&
              git checkout master &&
              git pull origin master &&
              sudo usermod -aG docker $USER &&
              sudo docker-compose up --build -d &&
              sudo cat dump.sql | docker exec -i db psql -U postgres